SELECT TOP (1000) [Column1]
      ,[item_name]
      ,[item_brand]
      ,[item_id]
      ,[item_variant]
      ,[item_product]
      ,[item_price]
      ,[item_bought]
      ,[item_discount]
      ,[item_price_previous]
      ,[item_star]
      ,[item_comment_number]
      ,[date]
  FROM [HASAKI].[dbo].[tonghop$]
